Fix/openai utils issue
f-lab-edu/please-just-texting pull request #13
Opened 2023-12-29 01:06 UTC by hwarang97

- fix muti reponse issue in openai_utils.py

2023-12-29 04:54 UTC, FlabKenneth commented
PR의 범위가 잘못 잡혀있는 것 같네요.
PR title은 `Fix/openai utils issue` 인데 실제 수정 범위는 타이핑, html, 로거 설정 등으로 보입니다.

2023-12-31 00:17 UTC, hwarang97 commented
fix로 PR을 잡았던 이유는 OpenAI 로부터 복수의 응답을 받는 현상을 오류라고 생각했고, 그걸 해걸한다는 의미였습니다.
제가 진행한 내용은 프롬프트 수정, json 파싱 기능 추가, 코멘트 제거, 함수 내 지역변수 이름 변경입니다.
버그 수정 및 코드 변경이므로 refactor라고 표현하는게 좋을까요? 

로거 내용은 이전 브런치에서 병합하면서 생겼던 커밋을 말씀하시는걸로 파악했습니다. 이전에 한 작업도 포함해서 PR의 이름을 고려하는것이 좋을까요?

2024-01-06 15:07 UTC, FlabKenneth commented
현 PR #13은 @hwarang97 님이 말씀해주신 것과 같이 아래 사항에 연관된 코드만 담겨있어야 합니다.

```plaintext
 OpenAI 로부터 복수의 응답을 받는 현상을 오류라고 생각했고, 그 문제를 해결.
```

즉슨 별도의 특별한 사유가 없는 이상 서로다른 PR의 파일 수정 이력이 섞이지 않고 독립적이어야 합니다.
모든 PR 작업은 아래와 같이 main을 기준으로 깨끗한 상태로 시작해야 하는 것을 염두해주세요!

- main으로 부터 새로운 브랜치 체크아웃
- PR 1 작업 (브랜치 각종 커밋 기록)
- main으로 체크아웃 (main의 head로 커밋 기록 clean)
- main으로 부터 새로운 브랜치 체크아웃
- PR 2 작업 (브랜치 각종 커밋 기록)
- main으로 체크아웃 (main의 head로 커밋 기록 clean)
- ...
- main으로 부터 새로운 브랜치 체크아웃
- PR N 작업 (브랜치 각종 커밋 기록)

2024-01-06 15:08 UTC, FlabKenneth commented
요약 드리면 이 PR의 `fix/xxx` 타이틀은 문제 없으나,
파일 수정 이력에 PR의 제목과 관계 없는 파일 수정이 존재하는 것이 문제입니다.

---

보통 업무에서는 정석적으로 볼 때는 PR에 관련 없는 파일은 모두 제거하고 다시 올려주셔야 하나
이번 PR만 예외적으로 허용하겠습니다!

2024-01-06 15:08 UTC, FlabKenneth requested changes
Resolve conflicts 요청드립니다.

2024-01-06 16:18 UTC, hwarang97 reviewed
LGTM

2024-01-15 13:17 UTC, hwarang97 reviewed
LGTM

2024-01-16 14:51 UTC, closed without merging